<?php

namespace ProcessWire;

class WesanoxMatrixContent extends WireData implements Module
{
    public static function getModuleInfo()
    {
        return array(
            'title' => 'wesanox Content Matrix',
            'summary' => 'The Matrix Helper Module for Processwire made by wesanox. It creates the Content Matrix.',
            'version' => '0.1.1',
            'author' => 'Frittenfritze',
            'href' => 'https://wesanox.de',
            'icon' => 'codepen',
            'singular' => true,
            'autoload' => true,
            'installs' => ['PageFrontEdit', 'CroppableImage3','WesanoxFrameworkPackage','WesanoxHelperFields'],
            'requires' => array(
                'ProcessWire>=3.0.210',
                'PHP>=8.0.0',
                'FieldtypeRepeaterMatrix>=0.0.9',
                'WesanoxFrameworkPackage>=0.0.1',
                'WesanoxHelperFields>=0.0.1',
                'WesanoxHelperForms>=0.0.1',
                'WesanoxHelperClasses>=0.0.1',
            ),
        );
    }

    protected array $internal_modules = [
        'PageFrontEdit'
    ];


    protected array $external_modules = [
        'CroppableImage3' => 'https://github.com/horst-n/CroppableImage3/archive/master.zip',
        'WesanoxFrameworkPackage' => 'https://github.com/wesanox/WesanoxFrameworkPackage/archive/refs/heads/main.zip',
        'WesanoxHelperFields' => 'https://github.com/wesanox/WesanoxHelperFields/archive/refs/heads/main.zip',
        'WesanoxHelperForms' => 'https://github.com/wesanox/WesanoxHelperForms/archive/refs/heads/main.zip'
    ];

    /**
     * @var Module|_Module|null $helper_classes
     * @var Module|_Module|null $helper_fields
     */
    protected Module|_Module|null $helper_fields;
    protected Module|_Module|null $helper_forms;
    protected Module|_Module|null $helper_classes;

    /**
     * @var array|string[]
     */
    protected array $forms_array = [];

    /**
     * @var array $fields_array
     */
    protected array $fields_array = [];

    /**
     * @var array $templates_content
     */
    protected array $templates_content = [
        'content_only'
    ];

    /**
     * @throws WirePermissionException
     */
    function __construct()
    {
        parent::__construct();

        $this->helper_classes = $this->modules->get('WesanoxHelperClasses');
        $this->helper_forms = $this->modules->get('WesanoxHelperForms');
        $this->helper_fields = $this->modules->get('WesanoxHelperFields');

        $this->forms_array = include $this->config->paths->WesanoxMatrixContent . 'config/forms.php';
        $this->fields_array = include $this->config->paths->WesanoxMatrixContent . 'config/fields.php';
    }

    /**
     * install function for the modul
     *
     * @return void
     * @throws WireException
     * @throws WirePermissionException
     */
    public function ___install() :void
    {
        /**
         * Install internal modules
         */
        foreach ($this->internal_modules as $module_name) {
            if (!$this->modules->isInstalled($module_name)) {
                $this->modules->get($module_name);
            }
        }

        /**
         * Install external modules
         */
        foreach ($this->external_modules as $module_name => $module_url) {
            if (!$this->modules->isInstalled($module_name)) {
                $this->helper_classes->downloadInstall($module_name, $module_url);
            }
        }

        /**
         * create forms
         */
        $this->helper_forms->createForm($this->forms_array);

        /**
         * create fields
         */
        foreach ($this->fields_array as $field_array) {
            $this->helper_fields->createFields($field_array);
        }

        /**
         * if not exists, create content only Page
         */
        foreach ($this->templates_content as $template_content) {
            $file = $this->config->paths->WesanoxMatrixContent . 'src/templates/template_' . $template_content . '.php';
            $file_target = $this->config->paths->templates . 'template_' . $template_content . '.php';

            if (!is_file($file_target)) {
                $this->files->copy($file, $file_target);
            }

            if ( !$this->templates->get('template_' . $template_content) ) {
                $fg = new Fieldgroup();
                $fg->name = 'template_' . $template_content;
                $fg->add('title');
                $fg->add('matrix_content');
                $fg->save();

                $t = new Template();
                $t->name = 'template_' . $template_content;
                $t->label = 'Content Only';
                $t->fieldgroup = $fg;
                $t->icon = 'File code o';
                $t->tags = 'Templates';
                $t->save();
            } else {
                $t = $this->fieldgroups->get('template_' . $template_content);
                $t->add('matrix_content');
                $t->save();
            }
        }
    }

    /**
     * uninstall the modul with the fields
     *
     * @return void
     * @throws WireException
     */
    public function ___uninstall(): void
    {
        /**
         * delete forms
         */
        $this->helper_forms->deleteForm($this->forms_array);

        /**
         * delete template files
         */
        foreach ($this->templates_content as $template_content) {
            $template_content = 'template_' . $template_content;
            $file = $this->config->paths->templates . $template_content . '.php';

            if (is_file($file)) {
                $this->files->unlink($file);
            }

            if ( $this->templates->get($template_content) ) {
                $t = $this->fieldgroups->get($template_content);
                $t->deleteAll();
                $t->save();

                $this->templates->delete($this->templates->get($template_content));
            }
        }

        /**
         * delete fields
         */
        $matrix_content = $this->fields->get('matrix_content');
        $this->fields->delete($matrix_content);

        $this->helper_fields->deleteFields($this->fields_array);

//        $this->modules->uninstall('CroppableImage3');
    }
}